### ISSUE TITLE
order arms as chromosomes in scalings

### ISSUE THREAD

**Issue by sergpolly** [open2c/open2c_examples#2]
@golobor could we change:
```
hg38_arms = hg38_arms[hg38_arms.chrom.isin(clr.chromnames)].reset_index(drop=True)
```
to 
```
hg38_arms = hg38_arms.set_index("chrom").loc[clr.chromnames].reset_index()
```
this way we are both subsetting arms down to the chromosomes present in the cooler and we are preserving the order of arms according to the chrom names

This would be helpful downstream for inter-chromosomal regions - as they have to be from the upper triangle - and it would be more concise to have them ordered right away.

Also it would be nice to pass hg38_arms through `bioframe.parse_regions` to assign them some names  - as those can be used later to reorder pivoted dataframe with trans-expected

**Comment by sergpolly** [comment]
changes are in https://github.com/open2c/open2c_examples/pull/3

**Comment by golobor** [comment]
agreed!
