### ISSUE TITLE
 IndexError: positional indexers are out-of-bounds in insulation score computation

### ISSUE THREAD

**Issue by yuanyuanhe1999** [open2c/open2c_examples#31]
Hi, 

When I run the code in tutorial "Insulation & boundaries" (https://cooltools.readthedocs.io/en/latest/notebooks/insulation_and_boundaries.html), I encountered an error in insulation score computation:
`insulation_table = insulation(clr, windows, verbose=True)`
Here are the full error messages:
`INFO:root:fallback to serial implementation.
INFO:root:Processing region chr2
INFO:root:Processing region chr17
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/indexing.py:1714, in _iLocIndexer._get_list_axis(self, key, axis)
   1713 try:
-> 1714     return self.obj._take_with_is_copy(key, axis=axis)
   1715 except IndexError as err:
   1716     # re-raise with different error message, e.g. test_getitem_ndarray_3d

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/generic.py:4150, in NDFrame._take_with_is_copy(self, indices, axis)
   4141 """
   4142 Internal version of the `take` method that sets the `_is_copy`
   4143 attribute to keep track of the parent dataframe (using in indexing
   (...)
   4148 See the docstring of `take` for full explanation of the parameters.
   4149 """
-> 4150 result = self.take(indices=indices, axis=axis)
   4151 # Maybe set copy if we didn't actually change the index.

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/generic.py:4130, in NDFrame.take(self, indices, axis, **kwargs)
   4126     indices = np.arange(
   4127         indices.start, indices.stop, indices.step, dtype=np.intp
   4128     )
-> 4130 new_data = self._mgr.take(
   4131     indices,
   4132     axis=self._get_block_manager_axis(axis),
   4133     verify=True,
   4134 )
   4135 return self._constructor_from_mgr(new_data, axes=new_data.axes).__finalize__(
   4136     self, method="take"
   4137 )

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/internals/managers.py:891, in BaseBlockManager.take(self, indexer, axis, verify)
    890 n = self.shape[axis]
--> 891 indexer = maybe_convert_indices(indexer, n, verify=verify)
    893 new_labels = self.axes[axis].take(indexer)

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/indexers/utils.py:282, in maybe_convert_indices(indices, n, verify)
    281     if mask.any():
--> 282         raise IndexError("indices are out-of-bounds")
    283 return indices

IndexError: indices are out-of-bounds

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
Cell In[4], line 4
      2 clr = cooler.Cooler(f'./cooltools_example_data/test.mcool::resolutions/{resolution}')
      3 windows = [3*resolution, 5*resolution, 10*resolution, 25*resolution]
----> 4 insulation_table = insulation(clr, windows, verbose=True)
      5 insulation_table

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/cooltools/api/insulation.py:713, in insulation(clr, window_bp, view_df, ignore_diags, clr_weight_name, min_frac_valid_pixels, min_dist_bad_bin, threshold, append_raw_scores, chunksize, verbose, nproc)
    709         raise ValueError(
    710             "Insulating boundary strength threshold can be Li, Otsu or a float"
    711         )
    712 # Calculate insulation score:
--> 713 ins_table = calculate_insulation_score(
    714     clr,
    715     view_df=view_df,
    716     window_bp=window_bp,
    717     ignore_diags=ignore_diags,
    718     min_dist_bad_bin=min_dist_bad_bin,
    719     append_raw_scores=append_raw_scores,
    720     clr_weight_name=clr_weight_name,
    721     chunksize=chunksize,
    722     verbose=verbose,
    723     nproc=nproc,
    724 )
    726 # Find boundaries:
    727 ins_table = find_boundaries(
    728     ins_table,
    729     min_frac_valid_pixels=min_frac_valid_pixels,
    730     min_dist_bad_bin=min_dist_bad_bin,
    731 )

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/cooltools/lib/common.py:541, in pool_decorator.<locals>.wrapper(*args, **kwargs)
    539     mymap = map
    540 try:
--> 541     result = func(*args, **kwargs, map_functor=mymap)
    542 finally:
    543     if pool is not None:

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/cooltools/api/insulation.py:275, in calculate_insulation_score(clr, window_bp, view_df, ignore_diags, min_dist_bad_bin, is_bad_bin_key, append_raw_scores, chunksize, clr_weight_name, verbose, nproc, map_functor)
    261 job = partial(
    262     _get_region_insulation,
    263     clr,
   (...)
    271     verbose,
    272 )
    273 ins_region_tables = map_functor(job, view_df[["chrom", "start", "end", "name"]].values)
--> 275 ins_table = pd.concat(ins_region_tables)
    276 return ins_table

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/reshape/concat.py:382, in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    379 elif copy and using_copy_on_write():
    380     copy = False
--> 382 op = _Concatenator(
    383     objs,
    384     axis=axis,
    385     ignore_index=ignore_index,
    386     join=join,
    387     keys=keys,
    388     levels=levels,
    389     names=names,
    390     verify_integrity=verify_integrity,
    391     copy=copy,
    392     sort=sort,
    393 )
    395 return op.get_result()

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/reshape/concat.py:445, in _Concatenator.__init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    442 self.verify_integrity = verify_integrity
    443 self.copy = copy
--> 445 objs, keys = self._clean_keys_and_objs(objs, keys)
    447 # figure out what our result ndim is going to be
    448 ndims = self._get_ndims(objs)

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/reshape/concat.py:504, in _Concatenator._clean_keys_and_objs(self, objs, keys)
    502     objs_list = [objs[k] for k in keys]
    503 else:
--> 504     objs_list = list(objs)
    506 if len(objs_list) == 0:
    507     raise ValueError("No objects to concatenate")

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/cooltools/api/insulation.py:331, in _get_region_insulation(clr, is_bad_bin_key, clr_weight_name, chunksize, window_bp, min_dist_bad_bin, ignore_diags, append_raw_scores, verbose, region)
    329 warnings.simplefilter("ignore", RuntimeWarning)
    330 # XXX -- updated insul_diamond
--> 331 ins_track, n_pixels, sum_balanced, sum_counts = insul_diamond(
    332     region_query,
    333     region_bins,
    334     window=win_bin,
    335     ignore_diags=ignore_diags,
    336     clr_weight_name=clr_weight_name,
    337 )
    338 ins_track[ins_track == 0] = np.nan
    339 ins_track = np.log2(ins_track)

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/cooltools/api/insulation.py:111, in insul_diamond(pixel_query, bins, window, ignore_diags, norm_by_median, clr_weight_name)
    108 diag_pixels = chunk[chunk.bin2_id - chunk.bin1_id <= (window - 1) * 2]
    110 if clr_weight_name:
--> 111     diag_pixels = cooler.annotate(diag_pixels, bins[[clr_weight_name]])
    112     diag_pixels["balanced"] = transform(diag_pixels)
    113     valid_pixel_mask = ~diag_pixels["balanced"].isnull().values

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/cooler/api.py:634, in annotate(pixels, bins, replace)
    631         bmin, bmax = 0, None
    632     ann1 = _loc_slice(bins, bmin, bmax)
    633     anns.append(
--> 634         ann1.iloc[bin1 - bmin]
    635         .rename(columns=lambda x: x + "1")
    636         .reset_index(drop=True)
    637     )
    639 # Select bin annotations that correspond to the bin2 IDs in the pixels df
    640 if "bin2_id" in columns:

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/indexing.py:1191, in _LocationIndexer.__getitem__(self, key)
   1189 maybe_callable = com.apply_if_callable(key, self.obj)
   1190 maybe_callable = self._check_deprecated_callable_usage(key, maybe_callable)
-> 1191 return self._getitem_axis(maybe_callable, axis=axis)

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/indexing.py:1743, in _iLocIndexer._getitem_axis(self, key, axis)
   1741 # a list of integers
   1742 elif is_list_like_indexer(key):
-> 1743     return self._get_list_axis(key, axis=axis)
   1745 # a single integer
   1746 else:
   1747     key = item_from_zerodim(key)

File /lustre/user/liclab/heyy/envs/deep_learning/lib/python3.9/site-packages/pandas/core/indexing.py:1717, in _iLocIndexer._get_list_axis(self, key, axis)
   1714     return self.obj._take_with_is_copy(key, axis=axis)
   1715 except IndexError as err:
   1716     # re-raise with different error message, e.g. test_getitem_ndarray_3d
-> 1717     raise IndexError("positional indexers are out-of-bounds") from err

**IndexError: positional indexers are out-of-bounds**
`
I also tried it with my own data, which contain all chromosomes in mouse genome, however, it also got the same error after process region of chr1 and chr2. So I guess it seems like something went wrong when combining results of two chromosomes.

I used exactly the same codes as the tutorial "Insulation & boundaries" used, and the version of packages are: cooltools 0.7.0; pandas 2.2.1.

Could you please help me to fix it? Thank you so much :)

**Comment by Phlya** [comment]
As a temporary solution, you can downgrade cooler to the previous version

**Comment by yuanyuanhe1999** [comment]
Thanks a lot! Which version do you recommend would be more stable and more likely to work fine with insulation score computation?

**Comment by Phlya** [comment]
You probably have v0.10.0, try v0.9.3

**Comment by yuanyuanhe1999** [comment]
Thanks a lot! It works fine with cooler 0.9.3.
