### ISSUE TITLE
use my own one instead of a bioframe to fetch the genomic features from the UCSC

### ISSUE THREAD

**Issue by wbszhu** [open2c/open2c_examples#9]
Hi, 
If I do want to use my own one instead of a bioframe to fetch the genomic features from the UCSC. 
What should I do?
For this part: 
>https://cooltools.readthedocs.io/en/latest/notebooks/contacts_vs_distance.html

Thanks.

**Comment by gfudenberg** [comment]
hi,
one option is to load a csv or tsv that has chrom,start,end,name columns with pd.read_csv. you can see more about bioframe.chromarms here: https://bioframe.readthedocs.io/en/latest/_modules/bioframe/extras.html#make_chromarms

also, just a heads up that some of the code used in contacts_vs_distance code is being streamlined, which should hopefully be a smoother experience as a user

**Comment by gfudenberg** [comment]
we should add a note to contacts_vs_distance notebook (and perhaps other notebooks) for what to do with non-standard genomes https://github.com/open2c/cooltools/issues/275

**Comment by wbszhu** [comment]
Thanks. very useful.

**Comment by gfudenberg** [comment]
https://github.com/open2c/open2c_examples/pull/13
